<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.0.1.2</Version>
    <AssemblyVersion>1.0.1.2</AssemblyVersion>
    <FileVersion>1.0.1.2</FileVersion>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Title></Title>
    <Company>FeltedRed</Company>
    <Copyright>Copyright © 2026 Detlef Schneider (FeltedRed/detlefs)</Copyright>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\workflows\build.yml" />
    <None Include=".github\workflows\release.yml" />
    <None Include="installer\VortexModLists.Installer.Bundle\VortexModLists.Installer.Bundle.wixproj" />
    <None Include="installer\VortexModLists.Installer.Msi\VortexModLists.Installer.Msi.wixproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Strings.de.resx">
      <DependentUpon>Strings.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Screenshots\" />
  </ItemGroup>

</Project>
